---  # 2022 04 18

name: "Tag"
on:
  push:
    tags:
      - 'v*'

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:

      - uses: peter-evans/repository-dispatch@v1.1.3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: Aprende-com/devops
          event-type: "lms-plugin-docker"
          client-payload: |
            {
              "repository": "${{ github.repository }}",
              "ref": "${{ github.ref }}",
            }
